/*
 * This file is generated by jOOQ.
 */
package com.todo.db.sql;


import com.todo.db.sql.tables.Databasechangelog;
import com.todo.db.sql.tables.Databasechangeloglock;
import com.todo.db.sql.tables.Task;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in todo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>todo.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = com.todo.db.sql.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>todo.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = com.todo.db.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>todo.task</code>.
     */
    public static final Task TASK = com.todo.db.sql.tables.Task.TASK;
}
