/*
 * This file is generated by jOOQ.
 */
package com.todo.db.sql;


import com.todo.db.sql.tables.Databasechangelog;
import com.todo.db.sql.tables.Databasechangeloglock;
import com.todo.db.sql.tables.Task;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todo extends SchemaImpl {

    private static final long serialVersionUID = 1068319202;

    /**
     * The reference instance of <code>todo</code>
     */
    public static final Todo TODO = new Todo();

    /**
     * The table <code>todo.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = com.todo.db.sql.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>todo.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = com.todo.db.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>todo.task</code>.
     */
    public final Task TASK = com.todo.db.sql.tables.Task.TASK;

    /**
     * No further instances allowed
     */
    private Todo() {
        super("todo", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Task.TASK);
    }
}
