/*
 * This file is generated by jOOQ.
 */
package com.todo.db.sql.tables.daos;


import com.todo.db.sql.tables.Task;
import com.todo.db.sql.tables.records.TaskRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskDao extends DAOImpl<TaskRecord, com.todo.db.sql.tables.pojos.Task, Integer> {

    /**
     * Create a new TaskDao without any configuration
     */
    public TaskDao() {
        super(Task.TASK, com.todo.db.sql.tables.pojos.Task.class);
    }

    /**
     * Create a new TaskDao with an attached configuration
     */
    public TaskDao(Configuration configuration) {
        super(Task.TASK, com.todo.db.sql.tables.pojos.Task.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.todo.db.sql.tables.pojos.Task object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.todo.db.sql.tables.pojos.Task> fetchById(Integer... values) {
        return fetch(Task.TASK.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.todo.db.sql.tables.pojos.Task fetchOneById(Integer value) {
        return fetchOne(Task.TASK.ID, value);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.todo.db.sql.tables.pojos.Task> fetchByDescription(String... values) {
        return fetch(Task.TASK.DESCRIPTION, values);
    }
}
